CREATE INDEX idx_news_category ON news(category_id);
CREATE INDEX idx_events_event_type ON events(event_type_id);
CREATE INDEX idx_events_host_member ON events(host_member_id);
CREATE INDEX idx_sessions_class_type ON schedule_sessions(class_type_id);
CREATE INDEX idx_learning_records_session ON learning_records(session_id);
CREATE INDEX idx_learning_records_member ON learning_records(member_id);
CREATE INDEX idx_learning_records_learner ON learning_records(learner_id);
CREATE INDEX idx_pairings_session ON session_pairings(session_id);
CREATE INDEX idx_pairings_member ON session_pairings(member_id);
CREATE INDEX idx_pairings_learner ON session_pairings(learner_id);
CREATE INDEX idx_member_registrations_session ON member_session_registrations(session_id);
CREATE INDEX idx_learner_registrations_session ON learner_session_registrations(session_id);
CREATE INDEX idx_news_published ON news(is_published, published_at DESC);
CREATE INDEX idx_learners_public ON learners(is_public);
CREATE INDEX idx_learners_invitation ON learners(invitation_status);
CREATE INDEX idx_members_active ON members(is_active);
CREATE INDEX idx_sessions_date ON schedule_sessions(date, class_type_id);
CREATE INDEX idx_sessions_status ON schedule_sessions(session_status);
CREATE INDEX idx_media_public ON media(is_public);
CREATE INDEX idx_stats_period ON stats(period_start, class_type_id, granularity);
